FROM ubuntu:latest

LABEL authors="Adam"

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

# Set the working directory
WORKDIR /api

# Copy the requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Copy the application code
COPY /api .

# Set the entrypoint to execute main.py
ENTRYPOINT ["python3", "api.py"]
